### ISSUE TITLE
Meaning of numbers in ClickData

### ISSUE THREAD

**Issue by hieuddo** [wuch15/KDD-NPA#1]
Hi,
Can you clarify what the number in _trainpos_ and _trainneg_ mean? Are those the _docid_s?
Thanks!

**Comment by wuch15** [comment]
Yes, the number in these lists are docids (the second column in the docmeta file, not the first one).

**Comment by hieudd98** [comment]
Can you please provide the requirements.txt for this repo?
Thanks!
