### ISSUE TITLE
IndexError: index 9335 is out of bounds for axis 0 with size 9335 site

### ISSUE THREAD

**Issue by shainaraza** [wuch15/KDD-NPA#3]
Hi
thanks for such amazing work!
I get the following error, please help with that
![image](https://user-images.githubusercontent.com/32249936/82684937-66286a80-9c21-11ea-8806-39083cfcf922.png)

Here 9335 are my documents

**Comment by shainaraza** [comment]
i think its solved by making             **browsed_news=news_words[all_user_pos[i]-1]**

however, i get the same error after 21 iteration in first epoch

**Comment by Pre-TrainedUM** [comment]
I guess this may be because some news indexes in the user history are not included in the "news_words" array? If so, you can just try filtering these news articles.

**Comment by wuch15** [comment]
I guess this may be because some news indexes in the user history are not included in the "news_words" array? If so, you can just try filtering these news articles.

**Comment by shainaraza** [comment]
its resolved now, thanks you

**Comment by frnk823** [comment]
> its resolved now, thanks you

hi, could you please tell me how you resolved this issue?
